micronaut:
  application:
    name: confirmation
  config-client:
    enabled: true
  metrics:
    enabled: true
  server:
    port: 8082
  caches:
    discovery-client:
      enabled: false
          
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS 
  metrics:
    enabled: true
    sensitive: false

tracing:
  zipkin:
    http:
      url: http://zipkin:9411
    enabled: true
    sampler:
      probability: 1 

consul:
  client:
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"
    config:
      format: YAML
    registration:
      enabled: true        
                             
jpa:
  default:
    packages-to-scan:
      - 'beautysalon.confirmation' 
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

rabbitmq:
  host: "rabbitmq"