// Code generated by protoc-gen-go. DO NOT EDIT.
// source: beautysalon/confirmation/proto/confirmation.proto

package confirmation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Appointment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CustomerName         string   `protobuf:"bytes,2,opt,name=CustomerName,proto3" json:"CustomerName,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=Date,proto3" json:"Date,omitempty"`
	StartTime            int32    `protobuf:"varint,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int32    `protobuf:"varint,5,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Duration             int32    `protobuf:"varint,6,opt,name=Duration,proto3" json:"Duration,omitempty"`
	TreatmentId          string   `protobuf:"bytes,7,opt,name=TreatmentId,proto3" json:"TreatmentId,omitempty"`
	TreatmentName        string   `protobuf:"bytes,8,opt,name=TreatmentName,proto3" json:"TreatmentName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Appointment) Reset()         { *m = Appointment{} }
func (m *Appointment) String() string { return proto.CompactTextString(m) }
func (*Appointment) ProtoMessage()    {}
func (*Appointment) Descriptor() ([]byte, []int) {
	return fileDescriptor_43243e512513168e, []int{0}
}

func (m *Appointment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Appointment.Unmarshal(m, b)
}
func (m *Appointment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Appointment.Marshal(b, m, deterministic)
}
func (m *Appointment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Appointment.Merge(m, src)
}
func (m *Appointment) XXX_Size() int {
	return xxx_messageInfo_Appointment.Size(m)
}
func (m *Appointment) XXX_DiscardUnknown() {
	xxx_messageInfo_Appointment.DiscardUnknown(m)
}

var xxx_messageInfo_Appointment proto.InternalMessageInfo

func (m *Appointment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Appointment) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *Appointment) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Appointment) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Appointment) GetEndTime() int32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Appointment) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Appointment) GetTreatmentId() string {
	if m != nil {
		return m.TreatmentId
	}
	return ""
}

func (m *Appointment) GetTreatmentName() string {
	if m != nil {
		return m.TreatmentName
	}
	return ""
}

func init() {
	proto.RegisterType((*Appointment)(nil), "Appointment")
}

func init() {
	proto.RegisterFile("beautysalon/confirmation/proto/confirmation.proto", fileDescriptor_43243e512513168e)
}

var fileDescriptor_43243e512513168e = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xbf, 0x4a, 0xc0, 0x30,
	0x10, 0xc6, 0x49, 0xed, 0xdf, 0xab, 0x3a, 0xdc, 0x14, 0xc4, 0xa1, 0x14, 0x87, 0x4e, 0x16, 0xf1,
	0x09, 0xc4, 0x3a, 0x74, 0x71, 0xa8, 0x7d, 0x81, 0xd4, 0x44, 0x08, 0x98, 0xa4, 0xa4, 0xd7, 0xc1,
	0xc7, 0xf6, 0x0d, 0x84, 0x03, 0xab, 0xdd, 0xee, 0xfb, 0xfd, 0x0e, 0xee, 0x3b, 0x78, 0x58, 0x8c,
	0xda, 0xe9, 0x6b, 0x53, 0x9f, 0xc1, 0xf7, 0xef, 0xc1, 0x7f, 0xd8, 0xe8, 0x14, 0xd9, 0xe0, 0xfb,
	0x35, 0x06, 0x0a, 0x27, 0x74, 0xcf, 0xa8, 0xfd, 0x16, 0x50, 0x3f, 0xad, 0x6b, 0xb0, 0x9e, 0x9c,
	0xf1, 0x84, 0xd7, 0x90, 0x8c, 0x5a, 0x8a, 0x46, 0x74, 0xd5, 0x94, 0x8c, 0x1a, 0x5b, 0xb8, 0x7c,
	0xde, 0x37, 0x0a, 0xce, 0xc4, 0x57, 0xe5, 0x8c, 0x4c, 0xd8, 0x9c, 0x18, 0x22, 0xa4, 0x83, 0x22,
	0x23, 0x2f, 0xd8, 0xf1, 0x8c, 0xb7, 0x50, 0xbd, 0x91, 0x8a, 0x34, 0x5b, 0x67, 0x64, 0xda, 0x88,
	0x2e, 0x9b, 0xfe, 0x00, 0x4a, 0x28, 0x5e, 0xbc, 0x66, 0x97, 0xb1, 0xfb, 0x8d, 0x78, 0x03, 0xe5,
	0xb0, 0x47, 0x6e, 0x28, 0x73, 0x56, 0x47, 0xc6, 0x06, 0xea, 0x39, 0x1a, 0xc5, 0x45, 0x47, 0x2d,
	0x0b, 0x3e, 0xf7, 0x1f, 0xe1, 0x1d, 0x5c, 0x1d, 0x91, 0xeb, 0x96, 0xbc, 0x73, 0x86, 0x4b, 0xce,
	0xaf, 0x3f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xcc, 0x70, 0x03, 0x2f, 0x01, 0x00, 0x00,
}
