micronaut:
  application:
    name: appointments
  config-client:
    enabled: true
  router:
    static-resources:
    swagger:
      paths: classpath:META-INF/swagger
      mapping: /swagger/**
  metrics:
    enabled: true
  server:
    port: -1
  caches:
    discovery-client:
      enabled: false
        
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS 
  metrics:
    enabled: true
    sensitive: false

tracing:
  zipkin:
    http:
      url: http://localhost:9411
    enabled: true
    sampler:
      probability: 1 

consul:
  client:
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
    config:
      format: YAML
    registration:
      enabled: true             
        
jpa:
  default:
    packages-to-scan:
      - 'beautysalon.appointments' 
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
                
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/appointments`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:docker}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}      
    
rabbitmq:
  host: "localhost"