version: "3.7"

services:
  zipkin:
    image: openzipkin/zipkin:2.17.0
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"
  treatments-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: docker 
    ports:
      - "27017:27017"
  appointments-db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: appointments
  treatments:
    build: ./treatments
    image: beautysalon-moleculer/treatments:1.0 
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - treatments-db
      - rabbitmq
  appointments:
    build: ./appointments
    image: beautysalon-moleculer/appointments:1.0 
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - rabbitmq
      - zipkin
      - appointments-db
  confirmation:
    build: ./confirmation
    image: beautysalon-moleculer/confirmation:1.0 
    restart: on-failure
    depends_on: 
      - rabbitmq
  prometheus:
    image: prom/prometheus:v2.13.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-docker.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: on-failure
    depends_on:
      - treatments
      - appointments
      - confirmation